### ISSUE TITLE
WebDav

### ISSUE THREAD

**Issue by miralem-cebic** [kareman/NTBTask#3]
I'm trying to use `/sbin/mount_webdav` and 
getting this error output:

   `usage: mount_webdav [-i] [-s] [-S] [-o options] [-v <volume name>]
    <WebDAV_URL> node`

In implementationfile of mount_webdav 'http://www.opensource.apple.com/source/webdavfs/webdavfs-252.8/mount.tproj/mount_webdav.c'

this error occurs when `argc < 2`; means when given arguments counting less than two. 

here is my code:

```
    NTBTask *task = [[NTBTask alloc] initWithLaunchPath:@"/sbin/mount_webdav"];
    task.arguments = @[ @"-i", @"'https://MYSERVER.TLD:443/WDav/'", @"/Users/me/Desktop/MountPoint" ];

    NSMutableString *result = [[NSMutableString alloc] init];

    task.outputHandler = ^(NSString *output)
    {
        [result appendString:output];
    };
    task.completionHandler = ^(NTBTask *thistask)
    {
        NSLog(@"Finished");
    };

    [task launch]; 
```

What I'm doing wrong?

**Comment by kareman** [comment]
Do you get the same error if you run the same command in the terminal?

**Comment by miralem-cebic** [comment]
In Terminal it's working! 
![mount_webdav](https://cloud.githubusercontent.com/assets/1866374/7883017/76022a08-0613-11e5-8684-e5e0d44f8cd0.png)

**Comment by kareman** [comment]
Yes but you're prompted for a username and password. If you're not being asked for that when using NTBTask it might be because mount_webdav sees that it was not called from a terminal session and thinks asking for input is pointless. You could try including the username and password in the url itself, but putting passwords in clear text right in the code obviously isn't secure. Is there an open server without password you could test with?

**Comment by miralem-cebic** [comment]
*The password I will use in my project is encrypted, I would decrypt it when the promt comes.

yes it's working without password.

```
    NTBTask *task = [[NTBTask alloc] initWithLaunchPath:@"/sbin/mount_webdav"];
    task.arguments = @[ @"http://ajaxfilebrowser.com/User4b1fea9", @"/Users/miralemcebic/Desktop/MP" ];

    NSMutableString *result = [[NSMutableString alloc] init];

    task.outputHandler = ^(NSString *output)
    {
        [result appendString:output];
    };
    task.completionHandler = ^(NTBTask *thistask)
    {
        NSLog(@"Finished");
    };

    [task launch];
```

INFO: ajaxfilebrowser.com creating a temp webdav for a user for 72hours.

I have tried something arround and found out it's the '-i' argument, that don't work. Even when calling `system("/sbin/mount_webdav -i http://ajaxfilebrowser.com/User4b1fea9 /Users/miralemcebic/Desktop/MP");` 

I think you can close this issue. It's not the problem of your NTBTask. Sorry :)

**Comment by kareman** [comment]
Hey no problem. If "-i" stands for "interactive" that would explain it.

**Comment by miralem-cebic** [comment]
I thought I can hang me in interactive mode and set username and password. 
Because 

`/sbin/mount_webdav "https://domain\username:password@SERVER.tld:443/wdav/" /Users/miralemcebic/Desktop/MP`

doesn't work. 

But thanks for taking time. Your wrapper is great :+1:
